#!/usr/bin/env python3
"""Vendor the department's ITR schemas + validation rules, with provenance.

    python scripts/fetch_schemas.py                 # download everything for AY 2026-27
    python scripts/fetch_schemas.py --from-dir ~/Downloads   # use files you downloaded by hand

Writes, under service/schema/AY2026-27/:
    itr1_schema.json, itr4_schema.json          the schemas, byte-for-byte
    itr1_validation_rules.pdf, itr4_...pdf       the validation-rules documents
    sources.json                                 url / original name / sha256 / retrieved_at
    SOURCES.md                                   the same, human-readable

Stdlib only. Re-run each filing season and whenever the dept publishes a new
schema version (it has revised schemas mid-season before) - then run the test
suite: a changed schema shows up as builder test failures, never silently.

The URLs below were read off https://www.incometax.gov.in/iec/foportal/downloads
on 2026-10-06. If a download 404s, the dept has moved the file: open that page,
download by hand, and use --from-dir.
"""

from __future__ import annotations

import argparse
import hashlib
import io
import json
import sys
import urllib.request
import zipfile
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PORTAL = "https://www.incometax.gov.in/iec/foportal/sites/default/files"

# target file name -> (download URL, accepted original names for --from-dir)
SOURCES = {
    "AY2026-27": {
        "itr1_schema.json": (f"{PORTAL}/2026-06/ITR-1_2026_Main_V1.1.json",
                             ["ITR-1_2026_Main_V1.1.json", "ITR-1_2026_Main_V1.1.zip"]),
        "itr4_schema.json": (f"{PORTAL}/2026-07/ITR-4_2026_Main_V1.1.json",
                             ["ITR-4_2026_Main_V1.1.json", "ITR-4_2026_Main_V1.1.zip"]),
        "itr1_validation_rules.pdf": (
            f"{PORTAL}/2026-05/CBDT_e-Filing_ITR%201_Validation%20Rules_AY%202026-27.pdf",
            ["CBDT_e-Filing_ITR 1_Validation Rules_AY 2026-27.pdf"]),
        "itr4_validation_rules.pdf": (
            f"{PORTAL}/2026-05/CBDT_e-Filing_ITR%204_Validation%20Rules_AY%202026-27.pdf",
            ["CBDT_e-Filing_ITR 4_Validation Rules_AY 2026-27.pdf"]),
        "itr1_schema_change_document.pdf": (
            f"{PORTAL}/2026-07/ITR%201_Schema%20change%20document_AY2026-27_V1.1.pdf",
            ["ITR 1_Schema change document_AY2026-27_V1.1.pdf"]),
        "itr4_schema_change_document.pdf": (
            f"{PORTAL}/2026-07/ITR%204_Schema%20change%20document_AY2026-27_V1.1_0.pdf",
            ["ITR 4_Schema change document_AY2026-27_V1.1_0.pdf"]),
    },
}


def _unzip_json(data: bytes) -> bytes:
    """Some years the schema ships zipped. Take the single .json inside."""
    with zipfile.ZipFile(io.BytesIO(data)) as z:
        names = [n for n in z.namelist() if n.lower().endswith(".json")]
        if len(names) != 1:
            raise SystemExit(f"expected exactly one .json in zip, found {names}")
        return z.read(names[0])


def _fetch(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": "itr-wala-schema-fetch/1.0"})
    with urllib.request.urlopen(req, timeout=60) as r:
        return r.read()


def _write_sources_md(d: Path, manifest: dict) -> None:
    lines = [f"# Vendored department files - {d.name}", "",
             "Generated by `scripts/fetch_schemas.py`. **Never hand-edit the vendored files** - "
             "`service/schema_store.py` refuses any file whose sha256 differs from `sources.json`.", "",
             "| File | Source | Original name | Retrieved (UTC) | sha256 |",
             "|---|---|---|---|---|"]
    for name, e in sorted(manifest.items()):
        lines.append(f"| `{name}` | {e['url']} | {e['original_name']} | {e['retrieved_at']} | `{e['sha256']}` |")
    lines += ["", "Re-check the downloads page every filing season: "
              "https://www.incometax.gov.in/iec/foportal/downloads", ""]
    (d / "SOURCES.md").write_text("\n".join(lines))


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--ay", default="AY2026-27", choices=sorted(SOURCES))
    ap.add_argument("--from-dir", type=Path, help="use files already downloaded into this folder")
    ap.add_argument("--only", nargs="*", help="limit to these target names")
    a = ap.parse_args()

    d = ROOT / "service" / "schema" / a.ay
    d.mkdir(parents=True, exist_ok=True)
    manifest_p = d / "sources.json"
    manifest = json.loads(manifest_p.read_text()) if manifest_p.exists() else {}

    failed = []
    for target, (url, originals) in SOURCES[a.ay].items():
        if a.only and target not in a.only:
            continue
        try:
            if a.from_dir:
                found = [a.from_dir / n for n in originals if (a.from_dir / n).exists()]
                if not found:
                    raise FileNotFoundError(f"none of {originals} in {a.from_dir}")
                src, data, origin = found[0].name, found[0].read_bytes(), f"manual download ({url})"
            else:
                data, src, origin = _fetch(url), url.rsplit("/", 1)[-1], url
        except Exception as e:  # noqa: BLE001 - report and carry on with the rest
            print(f"FAIL  {target}: {e}")
            failed.append(target)
            continue
        if src.lower().endswith(".zip") or data[:2] == b"PK" and target.endswith(".json"):
            data = _unzip_json(data)
        if target.endswith(".json"):
            json.loads(data.decode("utf-8-sig"))  # must at least parse
        (d / target).write_bytes(data)
        manifest[target] = {
            "url": origin,
            "original_name": src,
            "retrieved_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
            "sha256": hashlib.sha256(data).hexdigest(),
            "bytes": len(data),
        }
        print(f"OK    {target}  sha256={manifest[target]['sha256'][:16]}...")

    manifest_p.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n")
    _write_sources_md(d, manifest)
    print(f"\nWrote {manifest_p.relative_to(ROOT)} and SOURCES.md. Now run the tests:\n"
          "  python -m unittest discover -s service/tests -t .")
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
